INSERT INTO Restaurant VALUES('Rest1','1111','Carrer 1','Poble1',7,'molt bo','11111','10','');
INSERT INTO Restaurant VALUES('Rest2','2222','Carrer 2','Poble2',7,'molt bo','11111','10','');
INSERT INTO Restaurant VALUES('Rest3','3333','Carrer 3','Poble3',7,'molt bo','11111','10','');
INSERT INTO Restaurant VALUES('Rest4','4444','Carrer 4','Poble4',7,'molt bo','11111','10','');
INSERT INTO Restaurant VALUES('Rest5','5555','Carrer 5','Poble5',7,'molt bo','11111','10','');
INSERT INTO Restaurant VALUES('Rest6','6666','Carrer 6','Poble6',7,'molt bo','11111','10','');
INSERT INTO Restaurant VALUES('Rest7','7777','Carrer 7','Poble7',7,'molt bo','11111','10','');